import {createBrowserRouter, RouterProvider} from 'react-router-dom'
import Home from '../pages/home/index'
import './globals.css'
import React from 'react'
import { Outlet } from 'react-router-dom'

import CadastrarUsuario from '../pages/usuarios/cadastrarUsuario/index'

const router = createBrowserRouter([
    {
      path: "/",
      element: <App />,
      children:[
        {
            path: "/",
            element: <Home />
        },
        {
            path: "/usuario/cadastrarUsuario",
            element: <CadastrarUsuario />
        }
      ]
    },
    ])

export default function App() {
  return (
 
<RouterProvider router={router}/>

   
   
)
  
}

// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
